from models import RuntimeApp
from .react_generator import generate_react_files
from .express_generator import generate_express_files
from .mongo_generator import generate_mongo_files

def generate_project_files(app: RuntimeApp) -> dict:
    files = {}
    
    files.update(generate_react_files(app))
    files.update(generate_express_files(app))
    files.update(generate_mongo_files(app))
    
    files["README.md"] = f"""# Generated Application

This project was automatically generated by nl2app.

## Stack
- Frontend: React + React Router
- Backend: Express.js
- Database: MongoDB (Mongoose)

## Run Instructions
1. `cd backend` -> `npm install` -> `npm run dev`
2. `cd frontend` -> `npm install` -> `npm run dev`
"""

    # Phase 6: Deployment Configs
    files["vercel.json"] = """{
  "version": 2,
  "builds": [
    { "src": "frontend/package.json", "use": "@vercel/static-build" },
    { "src": "backend/server.js", "use": "@vercel/node" }
  ],
  "routes": [
    { "src": "/api/(.*)", "dest": "/backend/server.js" },
    { "src": "/(.*)", "dest": "/frontend/$1" }
  ]
}"""

    files["render.yaml"] = """services:
  - type: web
    name: generated-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: generated-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
"""

    files["netlify.toml"] = """[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200
"""
    
    return files
